### ISSUE TITLE
SKEWT Error; "ImportError: No module named h5py"

### ISSUE THREAD

**Issue by Atoossa** [cwebster2/pyMeteo#16]
Hello,
I installed the pyMeteo and upgraded my python. the h5py exist in my system. however the skews command can not be run as it can not find the h5py. I paste the message bellow. Please advise me how to resolve the issue. 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/skewt", line 11, in <module>
    from pymeteo import skewt
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymeteo/skewt.py", line 128, in <module>
    import h5py
ImportError: No module named h5py

Thanks
Atoossa

**Comment by cwebster2** [comment]
Please install the 'h5py' python module and try this again.

**Comment by cwebster2** [comment]
Closing this as stale.  Feel free to re-open if you need.
