### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by mahronid** [cwebster2/pyMeteo#28]
Traceback (most recent call last):
  File "/usr/local/bin/skewt", line 4, in <module>
    __import__('pkg_resources').run_script('pymeteo==1.0.1', 'skewt')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/pymeteo-1.0.1-py3.6.egg/EGG-INFO/scripts/skewt", line 160, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/pymeteo-1.0.1-py3.6.egg/EGG-INFO/scripts/skewt", line 99, in main
    skewt.plot_wrf(args.f, args.lat, args.lon, args.t, args.output)
  File "/usr/local/lib/python3.6/dist-packages/pymeteo-1.0.1-py3.6.egg/pymeteo/skewt.py", line 366, in plot_wrf
    p_surface = f.variables['PSFC'][time,j,i]
  File "netCDF4/_netCDF4.pyx", line 3961, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 4796, in netCDF4._netCDF4.Variable._get
IndexError

**Comment by cwebster2** [comment]
p_surface = f.variables['PSFC'][time,j,i]

Does your netcdf file have a variable named PSFC in it?  if it does, can you provide the dimensions of that variable in your file and the command you ran that produced this output?
